name: CMake

on: [push, pull_request]

env:
  #  Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:

    strategy:
      matrix:
        include:
          #- UBUNTU_VER: 20.04
          #  PG_VER: 10
          #- UBUNTU_VER: 20.04
          #  PG_VER: 11
#          - UBUNTU_VER: 20.04
#            PG_VER: 12
          #- UBUNTU_VER: 20.04
          #  PG_VER: 13
          #- UBUNTU_VER: 20.04
          #  PG_VER: 14
          #- UBUNTU_VER: 20.04
          #  PG_VER: 15
          ##- UBUNTU_VER: 20.04
          ##  PG_VER: 16
          #- UBUNTU_VER: 22.04
          #  PG_VER: 10
          #- UBUNTU_VER: 22.04
          #  PG_VER: 11
          #- UBUNTU_VER: 22.04
          #  PG_VER: 12
          #- UBUNTU_VER: 22.04
          #  PG_VER: 13
          - UBUNTU_VER: 22.04
            PG_VER: 
          #- UBUNTU_VER: 22.04
          #  PG_VER: 15
          #- UBUNTU_VER: 22.04
          #  PG_VER: 16

    runs-on: ubuntu-${{ matrix.UBUNTU_VER }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v3
      with:
        # with pgexodus
        submodules: recursive

    - name: Inspect image
      run: |
        pwd # /home/runner/work/exodusdb/exodusdb
        ls -l
        :
        : Installed postgresql
        :
        apt list --installed postgresql*
        :
        : Available postgresql
        :
        apt list postgresql*
        :
        : Remove all postgresql
        :
        : sudo apt purge -y postgresql* # remove unwanted versions of postgresql (14?)
        :
        sudo ./install.sh ${{ matrix.PG_VER }}

    - name: Prepare - Update repos
      run: sudo ./install.sh ${{ matrix.PG_VER }} P

    - name: Dependencies for build
      run: sudo ./install.sh ${{ matrix.PG_VER }} X

    - name: Build
      run: sudo ./install.sh ${{ matrix.PG_VER }} P

    - name: Dependencies for install
      run: sudo ./install.sh ${{ matrix.PG_VER }} Y

    - name: Install
      run: sudo ./install.sh ${{ matrix.PG_VER }} I

    - name: Test
      run: sudo ./install.sh ${{ matrix.PG_VER }} T
