name: CMake

on: [push, pull_request]

env:
  #  Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:

    strategy:
      matrix:
        include:
          #- UBUNTU_VER: 20.04
          #  PG_VER: 10
          #- UBUNTU_VER: 20.04
          #  PG_VER: 11
          - UBUNTU_VER: 20.04
            PG_VER: 12
          #- UBUNTU_VER: 20.04
          #  PG_VER: 13
          #- UBUNTU_VER: 20.04
          #  PG_VER: 14
          #- UBUNTU_VER: 20.04
          #  PG_VER: 15
          ##- UBUNTU_VER: 20.04
          ##  PG_VER: 16
          #- UBUNTU_VER: 22.04
          #  PG_VER: 10
          #- UBUNTU_VER: 22.04
          #  PG_VER: 11
          #- UBUNTU_VER: 22.04
          #  PG_VER: 12
          #- UBUNTU_VER: 22.04
          #  PG_VER: 13
          - UBUNTU_VER: 22.04
            PG_VER: 14
          #- UBUNTU_VER: 22.04
          #  PG_VER: 15
          #- UBUNTU_VER: 22.04
          #  PG_VER: 16

    runs-on: ubuntu-${{ matrix.UBUNTU_VER }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install all
      run: |
        pwd # /home/runner/work/exodusdb/exodusdb
        ls -l
        sudo ./install_all.sh ubuntu-${{ matrix.UBUNTU_VER }} ${{ matrix.PG_VER }}
