name: CMake

on: [push, pull_request]

env:
  #  Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:

    strategy:
      matrix:
        include:
          #
          # Latest Ubuntu with default Postgres version #
          #
          #- UBUNTU_VER: latest
          #  PG_VER:
          #
          # Default Postgres versions
          #
          #- UBUNTU_VER: 20.04
          #  PG_VER:
          #- UBUNTU_VER: 22.04
          #  PG_VER:
          #
          # Specific Postgres versions
          #
          #- UBUNTU_VER: 20.04
          #  PG_VER: 10
          #- UBUNTU_VER: 20.04
          #  PG_VER: 11
          #- UBUNTU_VER: 20.04
          #  PG_VER: 12
          #- UBUNTU_VER: 20.04
          #  PG_VER: 13
          #- UBUNTU_VER: 20.04
          #  PG_VER: 14
          #- UBUNTU_VER: 20.04
          #  PG_VER: 15
          #- UBUNTU_VER: 20.04
          #  PG_VER: 16
          #
          #- UBUNTU_VER: 22.04
          #  PG_VER: 10
          #- UBUNTU_VER: 22.04
          #  PG_VER: 11
          #- UBUNTU_VER: 22.04
          #  PG_VER: 12
          #- UBUNTU_VER: 22.04
          #  PG_VER: 13
          - UBUNTU_VER: 22.04
            PG_VER: 14
          #- UBUNTU_VER: 22.04
          #  PG_VER: 15
          #- UBUNTU_VER: 22.04
          #  PG_VER: 16

    # https://docs.github.com/en/actions/learn-github-actions/expressions
    #runs-on: ubuntu-${{ matrix.UBUNTU_VER }}
    runs-on: ubuntu-${{ matrix.UBUNTU_VER && matrix.UBUNTU_VER || 'latest' }}
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    steps:
    - uses: actions/checkout@v4
      with:
        # with pgexodus
        submodules: recursive

    - name: Inspect image
      run: |
        set -ex
        pwd # /home/runner/work/exodusdb/exodusdb
        ls -l
        :
        : Installed postgresql
        :
        apt list --installed postgresql*
        :
        : Available postgresql
        :
        : apt list postgresql-*
        :
        : Remove all postgresql
        :
        : sudo apt purge -y postgresql* # remove unwanted versions of postgresql (14?)
        :
        : sudo ./install.sh ${{ matrix.PG_VER }}
        env

    - name: Get dependencies for build
      run: env ./install.sh "${{ matrix.PG_VER }}" b

    - name: Build
      run: ./install.sh "${{ matrix.PG_VER }}" B

    - name: Get dependencies for install
      run: ./install.sh "${{ matrix.PG_VER }}" i

    - name: Install
      run: ./install.sh "${{ matrix.PG_VER }}" I

    - name: Test
      run: ./install.sh "${{ matrix.PG_VER }}" T
